# Generated by Django 3.2.4 on 2021-06-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Salaire',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Ville',
            field=models.CharField(default='Paris', max_length=100),
        ),
    ]
